project:
  type: website
  output-dir: docs

website:
  title: "Tero Jalkanen"
  favicon: logo-for-website-v2.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - icon: github
        href: https://github.com/TeroJii
        
format:
  html:
    theme: spacelab
    page-layout: full
    css: styles.css
    toc: true

execute:
  freeze: auto # re-render only when source file changes