project:
  type: website
  output-dir: docs

website:
  title: "Tero Jalkanen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - icon: github
        href: https://github.com/TeroJii
        
format:
  html:
    theme: spacelab
    page-layout: full
    css: styles.css
    toc: true



