project:
  type: website

website:
  title: "Tero's homepage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      # - href: talks.qmd
      #   text: Talks
      - href: blog.qmd
        text: Blog
      - icon: github
        href: https://github.com/TeroJii
        
format:
  html:
    theme: spacelab
    page-layout: full
    css: styles.css
    toc: true



