---
title: "Building your website with Quarto"
#author: "Tero Jalkanen"
date: "2022-12-28"
categories: [blog, quarto]
description: 'A brief story about how I built this website with Quarto'
---

This website is built with [Quarto](https://quarto.org/), which is an open-source publishing system, and it can be used for making reports, books, presentations, websites etc. I wanted to learn how to use Quarto for making a website, so I decided to make one for myself.

# Before we start

Building a website might seem intimidating. At least that's how I felt, having never done it before. Luckily, Quarto makes the process quite pleasant. I also found a couple of nice resources that walk you through the process. If you want to try it out I recommend reading the [websites](https://quarto.org/docs/websites) section on the Quarto website.
Albert Rapp has written a great overview on [how to setup a blog with Quarto](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html), which I found very helpful as an R user.

# What you will need

The latest version of RStudio includes a built-in version of Quarto. Updating RStudio is most likely the easiest way of installing Quarto. You will also need a [github](https://github.com) account.